# Affine Functions with 1 Feature

## import tensorflow and a layer

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

affine function이나 artificial neutron은 layer 단위에서 구현되기 때문에 Dense layer를 불러옴

## input setting

In [2]:
x= tf.constant([[10.]]) #input setting
print(x.shape)
print(x)

(1, 1)
tf.Tensor([[10.]], shape=(1, 1), dtype=float32)


## affine function generation

In [3]:
dense = Dense(units=1) #import an affine function
dense1 = Dense(units=1, activation='relu') #import an affine and activation function

y_tf = dense(x) #forward propagation + parameter initialization
print(y_tf)

tf.Tensor([[-15.44279]], shape=(1, 1), dtype=float32)


- dense 는 keras 에서 제공하는 Dense layer를 이용하여 하나의 affine function 을 만들었다
- x 값을 통과시켜 y_tf 값이 나온다

다시 말해서 dense 안에는 w, b가 들어있고, 위의 식은 'Z=X x W+ b'를 나타내는 식이다

## weight and bias

In [6]:
w, b = dense.get_weights() #get weight, bias
print(w,b)

[[-1.544279]] [0.]


## tensorflow계산과 manual로 계산한 값을 비교해보자

In [13]:
y_manual = tf.linalg.matmul(x, w) + b
# x 는 matrix의 형태이기 때문에 matrix multiplication 식을 사용하여 x*w를 계산하고 b를 더한다

print(y_manual)

tf.Tensor([[-4.277917]], shape=(1, 1), dtype=float32)


## Parameter Initialization

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant
# 내가 원하는 값으로 (여기서는 Constant를 사용해서) initialization을 해주겠다는 뜻 

x= tf.constant([[10.]]) #input setting

In [8]:
# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.)
print(w, b)

w_init, b_init = Constant(w), Constant(b)
#여기서 'Constant' = 'tf.keras.initializers.Constant()'
print(w_init, b_init)

tf.Tensor(10.0, shape=(), dtype=float32) tf.Tensor(20.0, shape=(), dtype=float32)
<keras.initializers.initializers_v2.Constant object at 0x000001F60A3F34F0> <keras.initializers.initializers_v2.Constant object at 0x000001F638D69880>


In [9]:
# import an affine function
dense = Dense(units=1,
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)
y_tf = dense(x)
w,b = dense.get_weights()
print(f'w: {w.shape, w}')
print(f'b: {b.shape, b}')

w: ((1, 1), array([[10.]], dtype=float32))
b: ((1,), array([20.], dtype=float32))


## summary

In [24]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

X = tf.constant([[20.]]) #input setting(Note: input -> matrix)
Dense = Dense(units=1) #import an affine function
Y_tf = Dense(X) # forward propagation + parameter initialization
W,B = Dense.get_weights() # get weight, bias

Y_manual = tf.linalg.matmul(X, W) + B # forward propagation by manually

print('========== Input/Weight/Bias ==========')
print(f'X: {X.shape, X.numpy()}')
print(f'W: {W.shape, W}') #weight는 기본적으로 numpy 값임
print(f'B: {B.shape, B}')

print('========== Output ==========')
print(f'Y_tf     : {Y_tf.shape, Y_tf.numpy()}')
print(f'Y_manual : {Y_manual.shape, Y_manual.numpy()}')

========== Input/Weight/Bias ==========
X: (TensorShape([1, 1]), array([[20.]], dtype=float32))
W: ((1, 1), array([[0.5275513]], dtype=float32))
B: ((1,), array([0.], dtype=float32))
========== Output ==========
Y_tf     : (TensorShape([1, 1]), array([[10.551025]], dtype=float32))
Y_manual : (TensorShape([1, 1]), array([[10.551025]], dtype=float32))


# Affine Function with n Feature

## import tensorflow and a layer

In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

## Input setting

In [16]:
x = tf.random.uniform(shape=(1,10), minval=0, maxval=10)
#random.uniform 은 tensorflow의 random 모듈 안에서
# 1이라는 row에 대해
# 0부터 10사이에 있는 값들을 10개 uniform하게 생성해주는 함수
# 즉 

print(x.shape, '\n', x)

(1, 10) 
 tf.Tensor(
[[7.5037374 1.3955057 0.7668841 8.940832  8.673107  8.414509  4.07658
  5.2791357 2.672174  5.5867968]], shape=(1, 10), dtype=float32)


## affine function generation

In [21]:
dense = Dense(units=1)
y_tf = dense(x)
W,B = dense.get_weights()
y_man = tf.linalg.matmul(x,W)+B


print('========== Input/Weight/Bias ==========')
print(f'X: {x.shape, x.numpy()}')
print(f'W: {W.shape},\n {W}') #weight는 기본적으로 numpy 값임
print(f'B: {B.shape, B}')

print('========== Output ==========')
print(f'y_tf     : {y_tf.shape, y_tf.numpy()}')
print(f'y_manual : {y_man.shape, y_man.numpy()}')

========== Input/Weight/Bias ==========
X: (TensorShape([1, 10]), array([[7.5037374, 1.3955057, 0.7668841, 8.940832 , 8.673107 , 8.414509 ,
        4.07658  , 5.2791357, 2.672174 , 5.5867968]], dtype=float32))
W: (10, 1),
 [[-0.5154078 ]
 [-0.04846495]
 [ 0.7124855 ]
 [-0.45953324]
 [-0.03345048]
 [-0.12407726]
 [-0.50046813]
 [ 0.56479996]
 [-0.17742729]
 [-0.40332168]]
B: ((1,), array([0.], dtype=float32))
========== Output ==========
y_tf     : (TensorShape([1, 1]), array([[-10.617437]], dtype=float32))
y_manual : (TensorShape([1, 1]), array([[-10.617437]], dtype=float32))
