# Activation Function

## import tensorflow & activation function

In [7]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

## input setting

In [8]:
x = tf.random.normal(shape=(1,5))

## activation function generation

In [11]:
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

## forward propagation

In [12]:
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

In [15]:
print(f'x:                   {x.shape} \n {x.numpy()}')
print(f'Sigmoid(Tensorflow): {y_sigmoid_tf.shape} \n {y_sigmoid_tf.numpy()}')
print(f'tanh(Tensorflow):    {y_tanh_tf.shape} \n {y_tanh_tf.numpy()}')
print(f'ReLU(Tensorflow):    {y_relu_tf.shape} \n {y_relu_tf.numpy()}')

x:                   (1, 5) 
 [[ 0.5542659  -1.5946397  -0.55887824 -0.7419671   0.35267764]]
Sigmoid(Tensorflow): (1, 5) 
 [[0.63512474 0.16873214 0.36380705 0.32257417 0.58726674]]
tanh(Tensorflow):    (1, 5) 
 [[ 0.5037106  -0.92085767 -0.5071447  -0.6303322   0.33874804]]
ReLU(Tensorflow):    (1, 5) 
 [[0.5542659  0.         0.         0.         0.35267764]]


## manual forward propagation

In [16]:
y_sigmoid_man = 1/(1+ exp(-x))
y_tanh_man = (exp(x)-exp(-x))/(exp(x)+exp(-x))
y_relu_man = maximum(x,0)


print(f'x:                   {x.shape} \n {x.numpy()}')
print(f'Sigmoid(manual): {y_sigmoid_man.shape} \n {y_sigmoid_man.numpy()}')
print(f'tanh(manual):    {y_tanh_man.shape} \n {y_tanh_man.numpy()}')
print(f'ReLU(manual):    {y_relu_man.shape} \n {y_relu_man.numpy()}')

x:                   (1, 5) 
 [[ 0.5542659  -1.5946397  -0.55887824 -0.7419671   0.35267764]]
Sigmoid(manual): (1, 5) 
 [[0.63512474 0.16873214 0.36380705 0.32257417 0.58726674]]
tanh(manual):    (1, 5) 
 [[ 0.5037106  -0.9208577  -0.5071447  -0.6303322   0.33874807]]
ReLU(manual):    (1, 5) 
 [[0.5542659  0.         0.         0.         0.35267764]]


# Activation in Dense layer

## import tensorflow and Dense

In [19]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

## Input setting

In [20]:
x = tf.random.normal(shape=(1,5)) # input setting

## import artifical neutrons and generate activation function

In [21]:
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

## forward propagaion

In [22]:
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

In [23]:
print(f'Artificial Neuron with Sigmoid: {y_sigmoid.shape}\n{y_sigmoid}')
print(f'Artificial Neuron with tanh   : {y_tanh.shape}\n{y_tanh}')
print(f'Artificial Neuron with ReLU   : {y_relu.shape}\n{y_relu}')

Artificial Neuron with Sigmoid: (1, 1)
[[0.40879223]]
Artificial Neuron with tanh   : (1, 1)
[[-0.8623651]]
Artificial Neuron with ReLU   : (1, 1)
[[0.]]


## forward propagation by manually

In [25]:
W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W)+b
a = 1/ (1+exp(-z))
print(f'Activation value(Tensorflow): {y_sigmoid.shape}\n{y_sigmoid.numpy()}')
print(f'Activation value(Manual)    : {a.shape}\n{a.numpy()}')

Activation value(Tensorflow): (1, 1)
[[0.40879223]]
Activation value(Manual)    : (1, 1)
[[0.40879223]]


# Minibatches

In [31]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 #set input parameters
x = tf.random.normal(shape=(N, n_feature)) # minibatch generation
#이 말은 matrix형태의 x가 8행 10열짜리
print(x.shape)

(8, 10)


In [34]:
dense = Dense(units=1, activation='relu') # artifical neuron import
y = dense(x) #forward propagaion

W, B = dense.get_weights() #우리가 궁금한건 weight 와 bias 의 생김새

In [36]:
print(f'Shape of x: {x.shape}')
print(f'Shape of W: {W.shape}')
print(f'Shape of B: {B.shape}')
            

Shape of x: (8, 10)
Shape of W: (10, 1)
Shape of B: (1,)


- Minibatch의 사이즈는 절대로 Weight와 Bias의 사이즈에 영향을 미치지 않는다
- 여기서 Feature 가 10개니까 Weight가 10개가 만들어지는 거고 Bias는 1개가 만들어지는 것


## When multiple minibatches

In [43]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 #set input parameters
x = tf.random.normal(shape=(N, n_feature)) # minibatch generation

dense = Dense(units=1, activation='sigmoid') # artifical neuron import
y_tf = dense(x) #forward propagaion (tensorflow)

W, B = dense.get_weights() #get weight and bias

y_man = tf.linalg.matmul(x, W)+B #forward propagation (manual)
y_man = 1/(1+tf.math.exp(-y_man))

#print results
print(f'Output(tensorflow)  : \n {y_tf.numpy()}')
print(f'Output(manual)      : \n {y_man.numpy()}')

Output(tensorflow)  : 
 [[0.39360315]
 [0.36543217]
 [0.22254945]
 [0.3948591 ]
 [0.55609214]
 [0.7829775 ]
 [0.762839  ]
 [0.36966085]]
Output(manual)      : 
 [[0.39360315]
 [0.36543217]
 [0.22254945]
 [0.3948591 ]
 [0.55609214]
 [0.7829775 ]
 [0.762839  ]
 [0.36966088]]
