# Dense Layer

In [26]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

#N : Data sample
#n_feature : Data features
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')

Y_tf=dense(X)
W,B = dense.get_weights()

#calculate with matrix multiplication
Z = matmul(X,W)+B
Y_man = 1/(1+exp(-Z))

#calculate with dot product
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x= X[x_idx]
    
    for nu_idx in range(n_neuron):
        w,b= W[:,nu_idx], B[nu_idx]
        z = tf.reduce_sum(x*w)+b
        a=1/(1+np.exp(-z))
        Y_man_vec[x_idx, nu_idx]=a
        

## Shapes of Dense Layers

In [28]:
print("==============")
print(f'X    :{X.shape}')
print(f'W    :{W.shape}')
print(f'B    :{B.shape}')
print(f'Y_tf :{Y_tf.shape}')



X    :(4, 10)
W    :(10, 3)
B    :(3,)
Y_tf :(4, 3)
Y_tf, row:batch-wise, column:neuron-wise
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.3609078 , 0.9084963 , 0.90643007],
       [0.96038854, 0.84438413, 0.85039103],
       [0.19278713, 0.50716895, 0.12326327],
       [0.5966667 , 0.7588585 , 0.90638953]], dtype=float32)>>
Y_man, row:batch-wise, column:neuron-wise
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.36090776, 0.9084963 , 0.90643007],
       [0.96038854, 0.8443842 , 0.850391  ],
       [0.19278713, 0.507169  , 0.12326327],
       [0.59666663, 0.75885856, 0.90638953]], dtype=float32)>>
Y_man_vec, row:batch-wise, column:neuron-wise
[[0.36090778 0.9084963  0.90643007]
 [0.96038852 0.84438417 0.85039103]
 [0.19278714 0.50716899 0.12326328]
 [0.59666667 0.75885855 0.90638952]]


## Output Calculations

In [ ]:
print("==============")
#print("Weights, row:batch-wise, column:neuron-wise")
#print(W)
print("Y_tf, row:batch-wise, column:neuron-wise")
print(Y_tf.numpy)

print("==============")
print("Y_man, row:batch-wise, column:neuron-wise")
print(Y_man.numpy)

print("==============")
print("Y_man_vec, row:batch-wise, column:neuron-wise")
print(Y_man_vec)