# Softmax Layers

## IO of  Softmax

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Activation

logits = tf.random.uniform(shape=(1,5), minval=-10, maxval=10)
print(logits)

tf.Tensor([[-3.5292315  8.746845   1.3904333  4.5532227 -1.2358141]], shape=(1, 5), dtype=float32)


In [7]:
softmax_value = Activation('softmax')(logits)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)#axis 1이라 함은 행렬에서 축방향으로 이어지는 방향을 말함

print(f"Logits:            {logits.numpy()}")
print(f"Probabilities:     {softmax_value.numpy()}")
print(f"Sum of softmax:    {softmax_sum.numpy()}")

Logits:            [[-3.5292315  8.746845   1.3904333  4.5532227 -1.2358141]]
Probabilities:     [[4.5895204e-06 9.8446423e-01 6.2856596e-04 1.4857057e-02 4.5476401e-05]]
Sum of softmax:    [0.99999994]


합이 거의 1인 것을 알 수 있다.

In [8]:
logits = tf.random.uniform(shape=(2,5), minval=-10, maxval=10) #2개의 데이터셈플, 5개의 클래스

softmax_value = Activation('softmax')(logits)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)#axis 1이라 함은 행렬에서 축방향으로 이어지는 방향을 말함

print(f"Logits:            \n{logits.numpy()}")
print(f"Probabilities:     \n{softmax_value.numpy()}")
print(f"Sum of softmax:    \n{softmax_sum.numpy()}")

Logits:            
[[ 2.0092058  2.3833542 -2.7985334 -2.8313518 -4.961643 ]
 [-9.767086  -7.2424173  2.5581284  5.264904  -6.662009 ]]
Probabilities:     
[[4.0473369e-01 5.8838272e-01 3.3051767e-03 3.1984670e-03 3.7998642e-04]
 [2.7772953e-07 3.4679410e-06 6.2574103e-02 9.3741602e-01 6.1964101e-06]]
Sum of softmax:    
[1. 1.]


## Softmax in Dense Layers

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8,5), minval=-10, maxval=10)
dense = Dense(units=8, activation='softmax')
Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[1.        1.0000001 1.        1.        1.        1.        1.
 1.       ], shape=(8,), dtype=float32)


# Multiclass Classifier

In [33]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model #subclass를 활용해보자

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        self.dense1 = Dense(units=8, activation='relu')
        self.dense2 = Dense(units=5, activation='relu')
        self.dense3 = Dense(units=3, activation='softmax')
    
    def call(self, x):
        
        print("=========================================== x")
        print(f"X_Shape:{x.shape}")
        print(f"X      :{x.numpy()}")
        
        x= self.dense1(x)
        print("=========================================== after layer 1")
        print(f"X_Shape:{x.shape}")
        print(f"X_D1   :{x.numpy()}")
        
        x= self.dense2(x)
        print("=========================================== after layer 2")
        print(f"X_Shape:{x.shape}")
        print(f"X_D2   :{x.numpy()}")
        
        x= self.dense3(x)
        print("=========================================== after layer 3")
        print(f"X_Shape:{x.shape}")
        print(f"X_D3   :{x.numpy()}")
        print(f"Sum of Vectors  : \n{tf.reduce_sum(x, axis=1)}")
        
        return x
    
model = TestModel()
X = tf.random.uniform(shape=(8, 3), minval=-10, maxval=10)
Y = model(X)


=========================================== x
X_Shape:(8, 3)
X      :[[ 7.324276   -1.2896776  -8.2765465 ]
 [ 5.17021    -0.50564957 -9.407146  ]
 [ 5.081236   -7.677765   -0.04022789]
 [-1.2168236   4.5332546   4.145191  ]
 [ 5.068819   -9.887573    5.781288  ]
 [ 4.021309    8.986099   -4.945507  ]
 [ 8.009718   -7.3444867   2.8395634 ]
 [-7.578597   -0.3091097  -2.2629786 ]]
=========================================== after layer 1
X_Shape:(8, 8)
X_D1   :[[0.0000000e+00 1.1732420e+00 9.7245312e+00 0.0000000e+00 2.9787357e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [9.7291684e-04 2.7603362e+00 8.2536297e+00 0.0000000e+00 1.1691597e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [3.6109006e-01 2.8024605e-01 7.8637457e+00 3.1413715e+00 3.9289494e+00
  2.6132839e+00 0.0000000e+00 1.6264093e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.1117155e-02 3.6935916e+00 1.9977278e+00]
 [0.0000000e+00 0.0000000e+00 6.4291921e+00 3.7410014e+00 5.5382133e+