# Datasets

## Datasets for Regression

In [3]:
import tensorflow as tf

N, n_feature = 8, 5 #N: Minibatch, x의 갯수: 5

t_weights = tf.constant([1,2,3,4,5], dtype=tf.float32) #이렇게 쓰는 것이 중요!
t_bias = tf.constant([10], dtype=tf.float32)
#즉, "x1*1 + x2*2 + x3*3 + x4*4 + x5*5 + 10"을 만들었음

print(t_weights)
print(t_bias)


tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([10.], shape=(1,), dtype=float32)


In [5]:
X= tf.random.normal(mean=0, stddev=1, shape=(N, n_feature)) 
#normal distribution 으로 평균은 0, standard deviation = 1, (8x5)형태의 데이터를 만듦
print(X)
print(X.shape, t_weights.shape, t_bias.shape)

tf.Tensor(
[[ 1.119729    0.84350216 -0.35043234 -0.5771035   0.7453682 ]
 [ 0.1398375  -0.03148724  0.18080221  0.20548262 -1.2209712 ]
 [ 0.2506688  -0.10894711  0.09617411 -0.46999386  1.3716466 ]
 [-0.98039514 -1.0028356   0.81693655 -0.54002124  0.8859946 ]
 [-0.3254515  -2.7461884   1.6782415   0.49033123  0.26678246]
 [-1.0642333  -0.6790227   0.76415354  0.01838655  0.925158  ]
 [-1.8343958  -0.04239063  0.9400056  -1.2537534   0.82207084]
 [ 1.1176574   1.7042673  -0.2567036  -0.5527641  -0.0339091 ]], shape=(8, 5), dtype=float32)
(8, 5) (5,) (1,)


In [10]:
Y= t_weights*X+t_bias
print(Y)
print(Y.shape)

tf.Tensor(
[[11.119729  11.687004   8.948703   7.691586  13.726841 ]
 [10.139837   9.937025  10.542407  10.821931   3.895144 ]
 [10.250669   9.782105  10.288523   8.120025  16.858234 ]
 [ 9.019605   7.9943285 12.4508095  7.8399153 14.429974 ]
 [ 9.674548   4.507623  15.034724  11.961325  11.333912 ]
 [ 8.935766   8.641954  12.29246   10.073546  14.62579  ]
 [ 8.165605   9.915218  12.820017   4.9849863 14.110354 ]
 [11.117658  13.408535   9.229889   7.7889433  9.830455 ]], shape=(8, 5), dtype=float32)
(8, 5)


x값이 8x5인데 weight를 곱하면 축에 있는 값들이 broad casting으로 전체적으로 곱해짐

In [12]:
Y= tf.reduce_sum(t_weights*X,axis=1) +t_bias
print(Y)
print(Y.shape)


tf.Tensor(
[13.173863   5.3363442 15.299555  11.734632  12.512134  14.569518
  9.996181  11.375479 ], shape=(8,), dtype=float32)
(8,)


In [15]:
#Result
print(f"X(shape): {X.shape} | X(dtype): {X.dtype}")
print(f"X.numpy \n {X.numpy()}")

print(f"Y(shape): {Y.shape} | Y(dtype): {Y.dtype}")
print(f"Y.numpy \n {Y.numpy()}")

X(shape): (8, 5) | X(dtype): <dtype: 'float32'>
X.numpy 
 [[ 1.119729    0.84350216 -0.35043234 -0.5771035   0.7453682 ]
 [ 0.1398375  -0.03148724  0.18080221  0.20548262 -1.2209712 ]
 [ 0.2506688  -0.10894711  0.09617411 -0.46999386  1.3716466 ]
 [-0.98039514 -1.0028356   0.81693655 -0.54002124  0.8859946 ]
 [-0.3254515  -2.7461884   1.6782415   0.49033123  0.26678246]
 [-1.0642333  -0.6790227   0.76415354  0.01838655  0.925158  ]
 [-1.8343958  -0.04239063  0.9400056  -1.2537534   0.82207084]
 [ 1.1176574   1.7042673  -0.2567036  -0.5527641  -0.0339091 ]]
Y(shape): (8,) | Y(dtype): <dtype: 'float32'>
Y.numpy 
 [13.173863   5.3363442 15.299555  11.734632  12.512134  14.569518
  9.996181  11.375479 ]
