# Dataset for Binary Classification

In [8]:
import tensorflow as tf

N, n_feature = 8, 5 #N: Minibatch, x의 갯수: 5

t_weights = tf.constant([1,2,3,4,5], dtype=tf.float32) #이렇게 쓰는 것이 중요!
t_bias = tf.constant([10], dtype=tf.float32)

X= tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y= tf.reduce_sum(t_weights*X,axis=1) +t_bias

#-------------------------------위에까지는 다 똑같음
#하지만 우리가 원하는 결과는 0 혹은 1임



In [9]:
print(Y)
print(Y.shape)

tf.Tensor(
[15.240879  3.827629 13.63904  10.436467 12.259761  8.074112 10.324648
  8.394736], shape=(8,), dtype=float32)
(8,)


여기서 보면 길이 8짜리 벡터가 만들어짐

In [10]:
Y = Y>5
print(Y)

tf.Tensor([ True False  True  True  True  True  True  True], shape=(8,), dtype=bool)


datatype 이 boolean 형태로 나옴

In [11]:
Y=tf.cast(Y, tf.int32)
print(Y)

tf.Tensor([1 0 1 1 1 1 1 1], shape=(8,), dtype=int32)


상기의 0 1 0 1 등이 Binary Cross Entropy 계산식에 들어가게 됨

In [14]:
#Result
print(f"X(shape): {X.shape} | X(dtype): {X.dtype}")
print(f"X.numpy \n {X.numpy()}")
print("Y = Y>5 경우에 대해서")
print(f"Y(shape): {Y.shape} | Y(dtype): {Y.dtype}")
print(f"Y.numpy \n {Y.numpy()}")


X(shape): (8, 5) | X(dtype): <dtype: 'float32'>
X.numpy 
 [[-1.0640454   0.34898704  0.67449933  0.07203194  0.6590648 ]
 [-0.62996453 -1.4568115   0.73012197 -1.0277418  -0.14163633]
 [-0.5367576  -0.07654183 -0.90644425  1.2867571   0.3802372 ]
 [-0.00447988 -0.8928643   0.03841023  0.13647847  0.3131063 ]
 [-1.5264395   0.9330726  -0.21508446  0.793832   -0.12200396]
 [-0.5216134   0.7957211  -1.933597   -0.35782346  0.84727377]
 [ 0.72812605  0.1361325   0.03972473  0.11070572 -0.24754809]
 [ 0.20698293 -0.55477214  1.2259041  -0.98946595 -0.08451023]]
Y = Y>5 경우에 대해서
Y(shape): (8,) | Y(dtype): <dtype: 'int32'>
Y.numpy 
 [1 0 1 1 1 1 1 1]
